export const testData = [
  {
    employer_name: "Infosys",
    employer_logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQKGQB_hmUVkx0HNjVmAKctp_E1gET48ocWSiKm&s=0",
    employer_website: "http://www.infosys.com",
    employer_company_type: "Information",
    job_publisher: "LinkedIn",
    job_id: "hO4waEcPOOsAAAAAAAAAAA==",
    job_employment_type: "FULLTIME",
    job_title: "React Developer",
    job_apply_link:"https://www.linkedin.com/jobs/view/python-developer-at-infosys-3542764368",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.5666,
    job_description: "Job Description Infosys is seeking a Python Developer. This position's primary responsibility will be to provide technical expertise and coordinate for day-to-day deliverables for the team. The chosen candidate will assist in the technical design of large business systems; builds applications, interfaces between applications, understands data security, retention, and recovery. The role holder should be able to research on technologies independently to recommend appropriate solutions & should contribute to technology-specific best practices & standards; contribute to success criteria from design through deployment, including, reliability, cost-effectiveness, performance, data integrity, maintainability and scalability; contributes expertise on significant application components, program languages, databases, operating systems, etc., and guides/mentors the team during the build and test phases. Candidate must be located within commuting distance of Pennington NJ/Jersey City NJ/NYC, NY/Dallas TX or be willing to relocate to ANY mentioned areas within 4-6 weeks. U.S. citizens and those authorized to work in the U.S. are encouraged to apply. We are unable to sponsor at this time. Required Qualifications • Bachelor's degree or foreign equivalent required from an accredited institution. Will also consider three years of progressive experience in the specialty in lieu of every year of education. • At least 2 years of Information Technology experience • Experience in Python server-side programming • Expert in Object Oriented Programming Concepts Preferred Qualifications • At least 2 years of experience in Python Server Side native programming and in framework • At least 2 years of experience in Java/J2EE technologies and experience in frameworks like Spring, Hibernate • At least 2 or more years of hands-on experience in JS Framework • At least 2 years of experience in software development life cycle. • At least 2 years of experience in Project life cycle activities on development and maintenance projects. • Willing to work in application/production support • Experience in Banking domain • Strong communication and Analytical skills • Ability to work in team in diverse/ multiple stakeholder environment • Experience and desire to work in a Global delivery environment The job entails sitting as well as working at a computer for extended periods of time. Should be able to communicate by telephone, email or face to face. Travel may be required as per the job requirements. About Us Infosys is a global leader in next-generation digital services and consulting. We enable clients in more than 50 countries to navigate their digital transformation. With over four decades of experience in managing the systems and workings of global enterprises, we expertly steer our clients through their digital journey. We do it by enabling the enterprise with an AI-powered core that helps prioritize the execution of change. We also empower the business with agile digital at scale to deliver unprecedented levels of performance and customer delight. Our always-on learning agenda drives their continuous improvement through building and transferring digital skills, expertise, and ideas from our innovation ecosystem. Infosys is an equal opportunity employer and all qualified applicants will receive consideration without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, protected veteran status, spouse of protected veteran, or disability.",
    job_is_remote: false,
    job_posted_at_timestamp: 1680040912,
    job_posted_at_datetime_utc: "2023-03-28T22:01:52.000Z",
    job_city: "Dallas",
    job_state: "TX",
    job_country: "US",
    job_latitude: 32.776665,
    job_longitude: -96.79699,
    job_benefits: null,
    job_google_link: "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=hO4waEcPOOsAAAAAAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2023-04-27T22:01:52.000Z",
    job_offer_expiration_timestamp: 1682632912,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 36,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification:false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
      degree_mentioned: true,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "The role holder should be able to research on technologies independently to recommend appropriate solutions & should contribute to technology-specific best practices & standards; contribute to success criteria from design through deployment, including, reliability, cost-effectiveness, performance, data integrity, maintainability and scalability; contributes expertise on significant application components, program languages, databases, operating systems, etc., and guides/mentors the team during the build and test phases",
        "Candidate must be located within commuting distance of Pennington NJ/Jersey City NJ/NYC, NY/Dallas TX or be willing to relocate to ANY mentioned areas within 4-6 weeks",
        "U.S. citizens and those authorized to work in the U.S. are encouraged to apply"
      ],
      Responsibilities: [
        "This position’s primary responsibility will be to provide technical expertise and coordinate for day-to-day deliverables for the team",
        "The chosen candidate will assist in the technical design of large business systems; builds applications, interfaces between applications, understands data security, retention, and recovery"
      ]
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113200",
    job_onet_job_zone: "4"
  },
  {
    employer_name: "Infosys",
    employer_logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQKGQB_hmUVkx0HNjVmAKctp_E1gET48ocWSiKm&s=0",
    employer_website: "http://www.infosys.com",
    employer_company_type: "Information",
    job_publisher: "LinkedIn",
    job_id: "hO4waEcPOOsAAAAAAAAAAA==c",
    job_employment_type: "FULLTIME",
    job_title: "React Developer",
    job_apply_link:"https://www.linkedin.com/jobs/view/python-developer-at-infosys-3542764368",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.5666,
    job_description: "Job Description Infosys is seeking a Python Developer. This position's primary responsibility will be to provide technical expertise and coordinate for day-to-day deliverables for the team. The chosen candidate will assist in the technical design of large business systems; builds applications, interfaces between applications, understands data security, retention, and recovery. The role holder should be able to research on technologies independently to recommend appropriate solutions & should contribute to technology-specific best practices & standards; contribute to success criteria from design through deployment, including, reliability, cost-effectiveness, performance, data integrity, maintainability and scalability; contributes expertise on significant application components, program languages, databases, operating systems, etc., and guides/mentors the team during the build and test phases. Candidate must be located within commuting distance of Pennington NJ/Jersey City NJ/NYC, NY/Dallas TX or be willing to relocate to ANY mentioned areas within 4-6 weeks. U.S. citizens and those authorized to work in the U.S. are encouraged to apply. We are unable to sponsor at this time. Required Qualifications • Bachelor's degree or foreign equivalent required from an accredited institution. Will also consider three years of progressive experience in the specialty in lieu of every year of education. • At least 2 years of Information Technology experience • Experience in Python server-side programming • Expert in Object Oriented Programming Concepts Preferred Qualifications • At least 2 years of experience in Python Server Side native programming and in framework • At least 2 years of experience in Java/J2EE technologies and experience in frameworks like Spring, Hibernate • At least 2 or more years of hands-on experience in JS Framework • At least 2 years of experience in software development life cycle. • At least 2 years of experience in Project life cycle activities on development and maintenance projects. • Willing to work in application/production support • Experience in Banking domain • Strong communication and Analytical skills • Ability to work in team in diverse/ multiple stakeholder environment • Experience and desire to work in a Global delivery environment The job entails sitting as well as working at a computer for extended periods of time. Should be able to communicate by telephone, email or face to face. Travel may be required as per the job requirements. About Us Infosys is a global leader in next-generation digital services and consulting. We enable clients in more than 50 countries to navigate their digital transformation. With over four decades of experience in managing the systems and workings of global enterprises, we expertly steer our clients through their digital journey. We do it by enabling the enterprise with an AI-powered core that helps prioritize the execution of change. We also empower the business with agile digital at scale to deliver unprecedented levels of performance and customer delight. Our always-on learning agenda drives their continuous improvement through building and transferring digital skills, expertise, and ideas from our innovation ecosystem. Infosys is an equal opportunity employer and all qualified applicants will receive consideration without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, protected veteran status, spouse of protected veteran, or disability.",
    job_is_remote: false,
    job_posted_at_timestamp: 1680040912,
    job_posted_at_datetime_utc: "2023-03-28T22:01:52.000Z",
    job_city: "Dallas",
    job_state: "TX",
    job_country: "US",
    job_latitude: 32.776665,
    job_longitude: -96.79699,
    job_benefits: null,
    job_google_link: "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=hO4waEcPOOsAAAAAAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2023-04-27T22:01:52.000Z",
    job_offer_expiration_timestamp: 1682632912,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 36,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification:false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
      degree_mentioned: true,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {},
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113200",
    job_onet_job_zone: "4"
  },
  {
    employer_name: "Infosys",
    employer_logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQKGQB_hmUVkx0HNjVmAKctp_E1gET48ocWSiKm&s=0",
    employer_website: "http://www.infosys.com",
    employer_company_type: "Information",
    job_publisher: "LinkedIn",
    job_id: "hO4waEcPOOsAAAAAAAAAAA==a",
    job_employment_type: "FULLTIME",
    job_title: "React Developer",
    job_apply_link:"https://www.linkedin.com/jobs/view/python-developer-at-infosys-3542764368",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.5666,
    job_description: "Job Description Infosys is seeking a Python Developer. This position's primary responsibility will be to provide technical expertise and coordinate for day-to-day deliverables for the team. The chosen candidate will assist in the technical design of large business systems; builds applications, interfaces between applications, understands data security, retention, and recovery. The role holder should be able to research on technologies independently to recommend appropriate solutions & should contribute to technology-specific best practices & standards; contribute to success criteria from design through deployment, including, reliability, cost-effectiveness, performance, data integrity, maintainability and scalability; contributes expertise on significant application components, program languages, databases, operating systems, etc., and guides/mentors the team during the build and test phases. Candidate must be located within commuting distance of Pennington NJ/Jersey City NJ/NYC, NY/Dallas TX or be willing to relocate to ANY mentioned areas within 4-6 weeks. U.S. citizens and those authorized to work in the U.S. are encouraged to apply. We are unable to sponsor at this time. Required Qualifications • Bachelor's degree or foreign equivalent required from an accredited institution. Will also consider three years of progressive experience in the specialty in lieu of every year of education. • At least 2 years of Information Technology experience • Experience in Python server-side programming • Expert in Object Oriented Programming Concepts Preferred Qualifications • At least 2 years of experience in Python Server Side native programming and in framework • At least 2 years of experience in Java/J2EE technologies and experience in frameworks like Spring, Hibernate • At least 2 or more years of hands-on experience in JS Framework • At least 2 years of experience in software development life cycle. • At least 2 years of experience in Project life cycle activities on development and maintenance projects. • Willing to work in application/production support • Experience in Banking domain • Strong communication and Analytical skills • Ability to work in team in diverse/ multiple stakeholder environment • Experience and desire to work in a Global delivery environment The job entails sitting as well as working at a computer for extended periods of time. Should be able to communicate by telephone, email or face to face. Travel may be required as per the job requirements. About Us Infosys is a global leader in next-generation digital services and consulting. We enable clients in more than 50 countries to navigate their digital transformation. With over four decades of experience in managing the systems and workings of global enterprises, we expertly steer our clients through their digital journey. We do it by enabling the enterprise with an AI-powered core that helps prioritize the execution of change. We also empower the business with agile digital at scale to deliver unprecedented levels of performance and customer delight. Our always-on learning agenda drives their continuous improvement through building and transferring digital skills, expertise, and ideas from our innovation ecosystem. Infosys is an equal opportunity employer and all qualified applicants will receive consideration without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, protected veteran status, spouse of protected veteran, or disability.",
    job_is_remote: false,
    job_posted_at_timestamp: 1680040912,
    job_posted_at_datetime_utc: "2023-03-28T22:01:52.000Z",
    job_city: "Dallas",
    job_state: "TX",
    job_country: "US",
    job_latitude: 32.776665,
    job_longitude: -96.79699,
    job_benefits: null,
    job_google_link: "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=hO4waEcPOOsAAAAAAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2023-04-27T22:01:52.000Z",
    job_offer_expiration_timestamp: 1682632912,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 36,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification:false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
      degree_mentioned: true,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {},
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113200",
    job_onet_job_zone: "4"
  },
]
